---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5

script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 4.10.0"
  - PUPPET_GEM_VERSION="~> 5.0.0"
  - PUPPET_GIT_URL="https://github.com/puppetlabs/puppet.git"
matrix:
  fast_finish: true
  allow_failures:
    - env: PUPPET_GIT_URL="https://github.com/puppetlabs/puppet.git"
